spring.datasource.url=jdbc:postgresql://localhost:5432/Movie
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.web.resources.statstaticic-locations=classpath:/static/
